name: Build and Deploy Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push FastAPI image
      run: |
        docker build ./Api-Farmacia -t ${{ secrets.DOCKER_USERNAME }}/api-farmacia:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/api-farmacia:latest

    - name: Build and push Next.js image
      run: |
        docker build ./Projeto-ModelFarma -t ${{ secrets.DOCKER_USERNAME }}/projeto-modelfarma:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/projeto-modelfarma:latest

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Deploy with Docker Compose
      run: |
        docker-compose -f .docker-compose.yml up -d
